// Import necessary modules from the mongoose library.
import mongoose, { Schema, Document } from 'mongoose';

// --- TypeScript Interface for Nested Comment Structure ---

/**
 * Defines the structure and types for an individual comment within a Tip.
 * This is used for type safety in the application code.
 */
interface IComment {
  userId: mongoose.Types.ObjectId; // The ID of the user who posted the comment
  text: string; // The content of the comment
  date: Date; // The time the comment was posted
}

// --- TypeScript Interface for Tip Document ---

/**
 * Defines the structure and types for the main Tip document.
 * Extends Mongoose's Document interface for database properties like _id.
 */
export interface ITip extends Document {
  authorId: mongoose.Types.ObjectId; // The ID of the user who authored the tip (Foreign Key)
  title: string;
  content: string;
  // Restricted set of allowed categories for the tip
  category: 'soil' | 'composting' | 'pests' | 'climate' | 'water'; 
  tags: string[]; // Array of descriptive tags
  likes: number; // Total count of likes
  likedBy: mongoose.Types.ObjectId[]; // Array of User IDs who liked the tip
  comments: IComment[]; // Array of nested comment objects
  isAIGenerated: boolean; // Flag to indicate if the content was generated by AI
  createdAt: Date; // Timestamp of creation (automatically managed by timestamps: true)
}

// --- Mongoose Nested Schema Definition (Comment) ---

// Defines the structure and validation rules for the nested Comment documents.
const CommentSchema = new Schema({
  // Foreign Key Link to User model
  userId: {
    type: Schema.Types.ObjectId,
    ref: 'User', // References the 'User' collection
    required: true
  },
  text: {
    type: String,
    required: true,
    maxlength: 300 // Limits comment length
  },
  date: {
    type: Date,
    default: Date.now // Timestamp for when the comment was created
  }
});

// --- Mongoose Main Schema Definition (Tip) ---

// Define the main schema (structure and validation rules) for the Tip model.
const TipSchema: Schema = new Schema({
  // Foreign Key Link to the Tip's author
  authorId: {
    type: Schema.Types.ObjectId,
    ref: 'User',
    required: true
  },
  title: {
    type: String,
    required: [true, 'Title is required'],
    trim: true,
    maxlength: [150, 'Title cannot exceed 150 characters']
  },
  content: {
    type: String,
    required: [true, 'Content is required'],
    maxlength: [2000, 'Content cannot exceed 2000 characters']
  },
  category: {
    type: String,
    // Restricts the category to a defined list of values
    enum: ['soil', 'composting', 'pests', 'climate', 'water'],
    required: true
  },
  // Array of strings for tagging/organization
  tags: [{
    type: String,
    trim: true
  }],
  // Total count of likes (denormalized for quick retrieval)
  likes: {
    type: Number,
    default: 0,
    min: 0
  },
  // Stores the list of users who liked the tip
  likedBy: [{
    type: Schema.Types.ObjectId,
    ref: 'User'
  }],
  // Embeds the CommentSchema as an array of sub-documents
  comments: [CommentSchema],
  // Metadata flag
  isAIGenerated: {
    type: Boolean,
    default: false
  }
}, {
  // Schema Options: Automatically add 'createdAt' and 'updatedAt' fields
  timestamps: true
});

// --- Database Indexing for Performance ---

// Index 1: Composite index for querying tips by category, ordered by newest first.
TipSchema.index({ category: 1, createdAt: -1 });
// Index 2: Index for sorting tips by popularity (highest likes first).
TipSchema.index({ likes: -1 });

// --- Export Mongoose Model ---

// Compiles the schema into a reusable Model and exports it.
// The model is named 'Tip', and it is strongly typed with the ITip interface.
export default mongoose.model<ITip>('Tip', TipSchema);